"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { DemoCalendar_v2414 } from "@/components/booking/demo-calendar"
import { Dialog, DialogContent, DialogTrigger } from "@/components/ui/dialog"
import { Bot, Sparkles, X } from "lucide-react"
import { motion } from "framer-motion"

const fadeIn = {
  initial: { opacity: 0, y: 20 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.5 }
}

const container = {
  hidden: { opacity: 0 },
  show: {
    opacity: 1,
    transition: {
      staggerChildren: 0.1
    }
  }
}

export const HeroSection_v2414 = () => {
  const [demoQuestion, setDemoQuestion] = useState("")
  const [demoResponse, setDemoResponse] = useState("")
  const [isGenerating, setIsGenerating] = useState(false)
  const [isVideoLoaded, setIsVideoLoaded] = useState(false)

  const handleDemoSubmit = async () => {
    setIsGenerating(true)
    // Simulate AI response
    await new Promise(resolve => setTimeout(resolve, 1500))
    setDemoResponse(`Here's a multiple-choice question based on your topic:

Q: ${demoQuestion}

A) Option 1
B) Option 2
C) Option 3
D) Option 4

Explanation: This is a sample explanation that would be generated by our AI system.`)
    setIsGenerating(false)
  }

  return (
    <section className="relative min-h-screen flex items-center justify-center overflow-hidden">
      {/* Video Background */}
      <div className="absolute inset-0 w-full h-full">
        <video
          autoPlay
          loop
          muted
          playsInline
          onLoadedData={() => setIsVideoLoaded(true)}
          className={`object-cover w-full h-full transition-opacity duration-1000 ${
            isVideoLoaded ? "opacity-100" : "opacity-0"
          }`}
        >
          <source src="/videos/hero-background.mp4" type="video/mp4" />
        </video>
        <div className="absolute inset-0 bg-gradient-to-b from-black/60 via-black/50 to-background" />
      </div>

      {/* Content */}
      <div className="container relative z-10 px-4 pt-24 pb-16">
        <motion.div 
          variants={container}
          initial="hidden"
          animate="show"
          className="grid lg:grid-cols-2 gap-12 items-center"
        >
          {/* Left column - Main content */}
          <motion.div 
            variants={fadeIn}
            className="space-y-8 text-white"
          >
            <motion.h1 
              variants={fadeIn}
              className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight"
            >
              Transform Learning with{" "}
              <span className="bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-transparent animate-gradient">
                AI-Powered
              </span>{" "}
              Assessment
            </motion.h1>
            
            <motion.p 
              variants={fadeIn}
              className="text-xl text-white/80"
            >
              Create engaging quizzes, assessments, and learning materials in seconds with our advanced AI technology.
            </motion.p>

            <motion.div 
              variants={fadeIn}
              className="flex flex-col sm:flex-row gap-4"
            >
              <Dialog>
                <DialogTrigger asChild>
                  <Button size="lg" className="text-lg group bg-white text-primary hover:bg-white/90">
                    <span>Book a Demo</span>
                    <motion.span
                      className="ml-2"
                      animate={{ x: [0, 4, 0] }}
                      transition={{ repeat: Infinity, duration: 1.5 }}
                    >
                      →
                    </motion.span>
                  </Button>
                </DialogTrigger>
                <DialogContent className="sm:max-w-[500px]">
                  <DemoCalendar_v2414 />
                </DialogContent>
              </Dialog>
              
              <Button size="lg" variant="outline" className="text-lg border-white text-white hover:bg-white hover:text-primary">
                View Pricing
              </Button>
            </motion.div>

            <motion.div 
              variants={fadeIn}
              className="flex items-center gap-4 text-sm text-white/80"
            >
              <div className="flex items-center gap-1">
                <Sparkles className="h-4 w-4" />
                <span>AI-Powered</span>
              </div>
              <div className="h-1 w-1 rounded-full bg-white/30" />
              <span>Free Trial Available</span>
              <div className="h-1 w-1 rounded-full bg-white/30" />
              <span>No Credit Card Required</span>
            </motion.div>
          </motion.div>

          {/* Right column - AI Demo */}
          <motion.div
            variants={fadeIn}
            whileHover={{ scale: 1.02 }}
            transition={{ type: "spring", stiffness: 300, damping: 20 }}
          >
            <Card className="p-6 shadow-lg border-white/10 backdrop-blur-sm bg-white/10">
              <div className="space-y-4">
                <div className="flex items-center gap-2 text-lg font-semibold text-white">
                  <Bot className="h-6 w-6 text-blue-400" />
                  <h2>Try Our AI Question Generator</h2>
                </div>

                <div className="space-y-4">
                  <Input
                    placeholder="Enter a topic or learning objective..."
                    value={demoQuestion}
                    onChange={(e) => setDemoQuestion(e.target.value)}
                    className="text-base bg-white/10 border-white/20 text-white placeholder:text-white/50"
                  />
                  
                  <Button 
                    onClick={handleDemoSubmit}
                    disabled={!demoQuestion || isGenerating}
                    className="w-full bg-blue-500 hover:bg-blue-600 text-white"
                  >
                    <span className={isGenerating ? "opacity-0" : "opacity-100"}>
                      Generate Question
                    </span>
                    {isGenerating && (
                      <motion.div
                        className="absolute inset-0 flex items-center justify-center"
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                      >
                        <div className="h-4 w-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                      </motion.div>
                    )}
                  </Button>

                  <motion.div
                    initial={{ opacity: 0, height: 0 }}
                    animate={{ 
                      opacity: demoResponse ? 1 : 0,
                      height: demoResponse ? "auto" : 0
                    }}
                    transition={{ duration: 0.3 }}
                  >
                    {demoResponse && (
                      <div className="mt-4 p-4 bg-white/10 rounded-lg whitespace-pre-wrap text-white">
                        {demoResponse}
                      </div>
                    )}
                  </motion.div>
                </div>
              </div>
            </Card>
          </motion.div>
        </motion.div>
      </div>
    </section>
  )
}
